# frozen_string_literal: true

lib = File.expand_path('lib', __dir__)

$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'flower_shop/version'

Gem::Specification.new do |spec|
  spec.name        = 'flower_shop'
  spec.version     = FlowerShop::VERSION
  spec.summary     = 'Flower_shop'
  spec.description = 'This gem is generated by using Thor generator'
  spec.authors     = ['Salman Sohail']
  spec.email       = ''
  spec.homepage    = 'https://salzam.com'
  spec.license     = 'MIT'
  spec.required_ruby_version = '>= 2.5.0'

  spec.add_development_dependency 'rubocop'
  spec.add_development_dependency 'rubocop-checkstyle_formatter'
  spec.add_development_dependency 'rubocop-rspec'

  # rspec suit
  spec.add_development_dependency 'rspec'
  spec.add_development_dependency 'shoulda-matchers'
  spec.add_development_dependency 'simplecov'
  spec.test_files = Dir['spec/**/*.rb']

  spec.files = Dir['README.md', 'lib/**/*']
  spec.require_path = 'lib'
end
